// AUTO-GENERATED by scripts/bake_barista_presets.py — do not edit by hand.
// Re-run `npm run bake` (or `python3 scripts/bake_barista_presets.py`) to refresh.
import type { Ingredients } from '../types/ingredients'

export const SOMMELIER_PRESETS: Record<string, Ingredients> = {
  "gold-apple-com": {
    "base": "vanilla",
    "color": {
      "accent_hex": "#fff8d6",
      "hex": "#f3e5ab"
    },
    "freshness": 0.4692,
    "inclusions": [
      {
        "amount": 0.6,
        "kind": "mint"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": 0.2001,
      "pc2": 0.2821,
      "pc3": -0.1542
    },
    "notes": [
      "closest to https://apple.com (Organic Milk)",
      "ordered/chaotic: leaning ordered"
    ],
    "request_id": "sommelier-apple-com",
    "sweetness": 0.6,
    "tartness": 0.4,
    "texture": "airy",
    "toppings": [
      {
        "amount": 0.66,
        "kind": "whipped_cream"
      }
    ],
    "url": "https://apple.com",
    "version": "ingredients-v0",
    "viscosity": 0.55
  },
  "gold-linear-app": {
    "base": "chocolate",
    "color": {
      "accent_hex": "#a87148",
      "hex": "#6b3f1d"
    },
    "freshness": 0.4173,
    "inclusions": [
      {
        "amount": 0.601,
        "kind": "mint"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": 0.2039,
      "pc2": -0.3035,
      "pc3": -0.4134
    },
    "notes": [
      "closest to https://linear.app (Cold Brew Espresso)",
      "ordered/chaotic: leaning ordered"
    ],
    "request_id": "sommelier-linear-app",
    "sweetness": 0.6,
    "tartness": 0.4,
    "texture": "airy",
    "toppings": [
      {
        "amount": 0.661,
        "kind": "whipped_cream"
      }
    ],
    "url": "https://linear.app",
    "version": "ingredients-v0",
    "viscosity": 0.551
  },
  "gold-rauno-me": {
    "base": "expired_milk",
    "color": {
      "accent_hex": "#eef0e3",
      "hex": "#d6d8c2"
    },
    "freshness": 0.6243,
    "inclusions": [
      {
        "amount": 0.551,
        "kind": "tech_debt_chunks"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": -0.0037,
      "pc2": -0.3794,
      "pc3": 0.4973
    },
    "notes": [
      "closest to https://rauno.me (Artisanal Mint)",
      "ordered/chaotic: leaning chaotic"
    ],
    "request_id": "sommelier-rauno-me",
    "sweetness": 0.3,
    "tartness": 0.6,
    "texture": "watery",
    "toppings": [
      {
        "amount": 0.551,
        "kind": "burnt_marshmallow"
      }
    ],
    "url": "https://rauno.me",
    "version": "ingredients-v0",
    "viscosity": 0.4993
  },
  "gold-stripe-com": {
    "base": "vanilla",
    "color": {
      "accent_hex": "#fff8d6",
      "hex": "#f3e5ab"
    },
    "freshness": 0.5754,
    "inclusions": [
      {
        "amount": 0.686,
        "kind": "sparkles"
      },
      {
        "amount": 0.4,
        "kind": "sprinkles"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": 0.5425,
      "pc2": 0.1695,
      "pc3": 0.3014
    },
    "notes": [
      "closest to https://stripe.com (Premium Vanilla)",
      "ordered/chaotic: leaning ordered"
    ],
    "request_id": "sommelier-stripe-com",
    "sweetness": 0.6,
    "tartness": 0.4,
    "texture": "smooth",
    "toppings": [
      {
        "amount": 0.763,
        "kind": "whipped_cream"
      }
    ],
    "url": "https://stripe.com",
    "version": "ingredients-v0",
    "viscosity": 0.6356
  },
  "gold-vercel-com": {
    "base": "vanilla",
    "color": {
      "accent_hex": "#fff8d6",
      "hex": "#f3e5ab"
    },
    "freshness": 0.5526,
    "inclusions": [
      {
        "amount": 0.589,
        "kind": "sparkles"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": 0.1554,
      "pc2": 0.3606,
      "pc3": 0.2102
    },
    "notes": [
      "closest to https://vercel.com (Salted Caramel)",
      "ordered/chaotic: leaning ordered"
    ],
    "request_id": "sommelier-vercel-com",
    "sweetness": 0.6,
    "tartness": 0.4,
    "texture": "airy",
    "toppings": [
      {
        "amount": 0.647,
        "kind": "whipped_cream"
      }
    ],
    "url": "https://vercel.com",
    "version": "ingredients-v0",
    "viscosity": 0.5388
  },
  "gunk-arngren-net": {
    "base": "fish",
    "color": {
      "accent_hex": "#9bbac3",
      "hex": "#4f7c8c"
    },
    "freshness": 0.4095,
    "inclusions": [
      {
        "amount": 0.637,
        "kind": "tech_debt_chunks"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": -0.349,
      "pc2": 0.471,
      "pc3": -0.4527
    },
    "notes": [
      "closest to https://arngren.net (The Deep Sea Shake)",
      "ordered/chaotic: leaning chaotic"
    ],
    "request_id": "sommelier-arngren-net",
    "sweetness": 0.3,
    "tartness": 0.6,
    "texture": "watery",
    "toppings": [
      {
        "amount": 0.637,
        "kind": "lint_dust"
      }
    ],
    "url": "https://arngren.net",
    "version": "ingredients-v0",
    "viscosity": 0.4302
  },
  "gunk-art-yale-edu": {
    "base": "expired_milk",
    "color": {
      "accent_hex": "#eef0e3",
      "hex": "#d6d8c2"
    },
    "freshness": 0.4498,
    "inclusions": [
      {
        "amount": 0.653,
        "kind": "tech_debt_chunks"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": -0.4135,
      "pc2": -0.5099,
      "pc3": -0.251
    },
    "notes": [
      "closest to https://art.yale.edu (Curdled Milk)",
      "ordered/chaotic: leaning chaotic"
    ],
    "request_id": "sommelier-art-yale-edu",
    "sweetness": 0.3,
    "tartness": 0.6,
    "texture": "watery",
    "toppings": [
      {
        "amount": 0.653,
        "kind": "lint_dust"
      }
    ],
    "url": "https://art.yale.edu",
    "version": "ingredients-v0",
    "viscosity": 0.4173
  },
  "gunk-berkshirehathaway-com": {
    "base": "expired_milk",
    "color": {
      "accent_hex": "#eef0e3",
      "hex": "#d6d8c2"
    },
    "freshness": 0.4835,
    "inclusions": [
      {
        "amount": 0.65,
        "kind": "tech_debt_chunks"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": -0.3997,
      "pc2": -0.1383,
      "pc3": -0.0827
    },
    "notes": [
      "closest to https://berkshirehathaway.com (Expired Water)",
      "ordered/chaotic: leaning chaotic"
    ],
    "request_id": "sommelier-berkshirehathaway-com",
    "sweetness": 0.3,
    "tartness": 0.6,
    "texture": "watery",
    "toppings": [
      {
        "amount": 0.65,
        "kind": "lint_dust"
      }
    ],
    "url": "https://berkshirehathaway.com",
    "version": "ingredients-v0",
    "viscosity": 0.4201
  },
  "gunk-lingscars-com": {
    "base": "strawberry",
    "color": {
      "accent_hex": "#ffd1e8",
      "hex": "#ff4da6"
    },
    "freshness": 0.5727,
    "inclusions": [
      {
        "amount": 0.591,
        "kind": "sparkles"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": 0.1655,
      "pc2": -0.4127,
      "pc3": 0.2909
    },
    "notes": [
      "closest to https://lingscars.com (Sour Candy & Fish)",
      "ordered/chaotic: leaning ordered"
    ],
    "request_id": "sommelier-lingscars-com",
    "sweetness": 0.6,
    "tartness": 0.4,
    "texture": "airy",
    "toppings": [
      {
        "amount": 0.65,
        "kind": "whipped_cream"
      }
    ],
    "url": "https://lingscars.com",
    "version": "ingredients-v0",
    "viscosity": 0.5414
  },
  "gunk-rudgwicksteamshow-co-uk": {
    "base": "burnt_rubber",
    "color": {
      "accent_hex": "#5e5e5e",
      "hex": "#2b2b2b"
    },
    "freshness": 0.5378,
    "inclusions": [
      {
        "amount": 0.582,
        "kind": "tech_debt_chunks"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": -0.1261,
      "pc2": 0.3818,
      "pc3": 0.1512
    },
    "notes": [
      "closest to https://rudgwicksteamshow.co.uk (Rusty Iron Shavings)",
      "ordered/chaotic: leaning chaotic"
    ],
    "request_id": "sommelier-rudgwicksteamshow-co-uk",
    "sweetness": 0.3,
    "tartness": 0.6,
    "texture": "watery",
    "toppings": [
      {
        "amount": 0.582,
        "kind": "burnt_marshmallow"
      }
    ],
    "url": "https://rudgwicksteamshow.co.uk",
    "version": "ingredients-v0",
    "viscosity": 0.4748
  },
  "wasabi-craigslist-org": {
    "base": "vanilla",
    "color": {
      "accent_hex": "#fff8d6",
      "hex": "#f3e5ab"
    },
    "freshness": 0.4043,
    "inclusions": [
      {
        "amount": 0.67,
        "kind": "mint"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": 0.4798,
      "pc2": -0.0998,
      "pc3": -0.4783
    },
    "notes": [
      "closest to https://craigslist.org (Plain Tap Water)",
      "ordered/chaotic: leaning ordered"
    ],
    "request_id": "sommelier-craigslist-org",
    "sweetness": 0.6,
    "tartness": 0.4,
    "texture": "airy",
    "toppings": [
      {
        "amount": 0.744,
        "kind": "whipped_cream"
      }
    ],
    "url": "https://craigslist.org",
    "version": "ingredients-v0",
    "viscosity": 0.62
  },
  "wasabi-yahoo-co-jp": {
    "base": "expired_milk",
    "color": {
      "accent_hex": "#eef0e3",
      "hex": "#d6d8c2"
    },
    "freshness": 0.5953,
    "inclusions": [
      {
        "amount": 0.664,
        "kind": "tech_debt_chunks"
      }
    ],
    "meta": {
      "baseline_id": "cellar-urls-v0",
      "confidence": 1.0,
      "model_id": "dummy",
      "pc1": -0.4552,
      "pc2": 0.1788,
      "pc3": 0.3813
    },
    "notes": [
      "closest to https://yahoo.co.jp (Matcha Ginger)",
      "ordered/chaotic: leaning chaotic"
    ],
    "request_id": "sommelier-yahoo-co-jp",
    "sweetness": 0.3,
    "tartness": 0.6,
    "texture": "watery",
    "toppings": [
      {
        "amount": 0.664,
        "kind": "burnt_marshmallow"
      }
    ],
    "url": "https://yahoo.co.jp",
    "version": "ingredients-v0",
    "viscosity": 0.409
  }
}

export const SOMMELIER_PRESET_KEYS = Object.keys(SOMMELIER_PRESETS)
