"""Bake Sommelier output for every cellar URL into Barista-loadable presets.

Reads real photographer embeddings from
``baselines/embeddings/baseline_embeddings.jsonl`` (built by
``python -m photographer baseline build``) and projects each cellar URL through
sommelier to produce canonical Ingredients. Writes
``barista/src/data/sommelierPresets.ts`` so the Barista preset picker shows
real Sommelier output for the cellar.

Run from repo root:
    python3 scripts/bake_barista_presets.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "src"))

from photographer.baseline import load_baseline
from sommelier.taste import ingredients_from_embeddings

OUT = ROOT / "barista" / "src" / "data" / "sommelierPresets.ts"

# Fields Barista's TS Ingredients.meta currently declares — keep this in lockstep
# with barista/src/types/ingredients.ts. Sommelier emits richer meta
# (discovered_axes, nearest_anchor) that we strip until Barista's type opts in.
META_KEEP = {"pc1", "pc2", "pc3", "confidence", "baseline_id", "model_id"}


def _slug(url: str) -> str:
    return (
        url.replace("https://", "")
        .replace("http://", "")
        .rstrip("/")
        .replace(".", "-")
        .replace("/", "-")
        .lower()
    )


def _trim_meta(ing: dict) -> dict:
    meta = ing.get("meta") or {}
    ing["meta"] = {k: v for k, v in meta.items() if k in META_KEEP}
    return ing


def main() -> int:
    try:
        meta, baseline_items = load_baseline()
    except FileNotFoundError as exc:
        print(
            f"Error: {exc}\n"
            f"Run `python -m photographer baseline build` first to populate "
            f"baselines/embeddings/.",
            file=sys.stderr,
        )
        return 2

    presets: dict[str, dict] = {}
    for item in baseline_items:
        target_embedding = item["embedding"]
        ing = ingredients_from_embeddings(
            target_embedding=target_embedding,
            baseline_items=baseline_items,
            request_id=f"sommelier-{_slug(item['url'])}",
            url=item["url"],
            baseline_id=meta["baseline_id"],
            model_id=meta["model_id"],
            pca_components=3,
        )
        _trim_meta(ing)
        presets[f"{item['label']}-{_slug(item['url'])}"] = ing

    body = json.dumps(presets, indent=2, sort_keys=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/bake_barista_presets.py — do not edit by hand.\n"
        "// Re-run `npm run bake` (or `python3 scripts/bake_barista_presets.py`) to refresh.\n"
        "import type { Ingredients } from '../types/ingredients'\n"
        "\n"
        f"export const SOMMELIER_PRESETS: Record<string, Ingredients> = {body}\n"
        "\n"
        "export const SOMMELIER_PRESET_KEYS = Object.keys(SOMMELIER_PRESETS)\n",
        encoding="utf-8",
    )
    print(
        f"Baked {len(presets)} presets from {meta['model_id']} embeddings "
        f"(dim={meta['embedding_dim']}) → {OUT.relative_to(ROOT)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
