"""Bake Sommelier output for every cellar URL into Barista-loadable presets.

Generates ``barista/src/data/sommelierPresets.ts`` from
``baselines/cellar_urls_v0.json`` using deterministic dummy embeddings, so the
Barista preset picker can render real Sommelier ``Ingredients`` alongside its
hand-crafted mocks.

Run from repo root:
    python3 scripts/bake_barista_presets.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from sommelier.dummy import dummy_embedding_for_key, load_cellar_urls
from sommelier.taste import ingredients_from_embeddings

CELLAR = ROOT / "baselines" / "cellar_urls_v0.json"
OUT = ROOT / "barista" / "src" / "data" / "sommelierPresets.ts"
EMBED_DIM = 64

# Fields Barista's TS Ingredients.meta currently declares — keep this in lockstep
# with barista/src/types/ingredients.ts. Sommelier emits richer meta
# (discovered_axes, nearest_anchor) that we strip until Barista's type opts in.
META_KEEP = {"pc1", "pc2", "pc3", "confidence", "baseline_id", "model_id"}


def _slug(url: str) -> str:
    return (
        url.replace("https://", "")
        .replace("http://", "")
        .rstrip("/")
        .replace(".", "-")
        .replace("/", "-")
        .lower()
    )


def _trim_meta(ing: dict) -> dict:
    meta = ing.get("meta") or {}
    ing["meta"] = {k: v for k, v in meta.items() if k in META_KEEP}
    return ing


def main() -> int:
    cellar = load_cellar_urls(CELLAR)

    baseline_items = [
        {
            "label": it["label"],
            "url": it["url"],
            "flavor_profile": it.get("flavor_profile", ""),
            "why": it.get("why", ""),
            "embedding": dummy_embedding_for_key(it["url"], embedding_dim=EMBED_DIM),
        }
        for it in cellar
    ]

    presets: dict[str, dict] = {}
    for it in cellar:
        target = dummy_embedding_for_key(it["url"], embedding_dim=EMBED_DIM)
        ing = ingredients_from_embeddings(
            target_embedding=target,
            baseline_items=baseline_items,
            request_id=f"sommelier-{_slug(it['url'])}",
            url=it["url"],
            baseline_id="cellar-urls-v0",
            model_id="dummy",
            pca_components=3,
        )
        _trim_meta(ing)
        presets[f"{it['label']}-{_slug(it['url'])}"] = ing

    body = json.dumps(presets, indent=2, sort_keys=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// AUTO-GENERATED by scripts/bake_barista_presets.py — do not edit by hand.\n"
        "// Re-run `npm run bake` (or `python3 scripts/bake_barista_presets.py`) to refresh.\n"
        "import type { Ingredients } from '../types/ingredients'\n"
        "\n"
        f"export const SOMMELIER_PRESETS: Record<string, Ingredients> = {body}\n"
        "\n"
        "export const SOMMELIER_PRESET_KEYS = Object.keys(SOMMELIER_PRESETS)\n",
        encoding="utf-8",
    )
    print(f"Baked {len(presets)} presets → {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
